# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/FEARFRED',
                'doc_host': 'https://professorwug.github.io',
                'git_url': 'https://github.com/professorwug/FEARFRED',
                'lib_path': 'FEARFRED'},
  'syms': {'FEARFRED.core': {'FEARFRED.core.foo': ('core.html#foo', 'FEARFRED/core.py')}}}